import { mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { blobAvailable, loadTripBlob, saveTripBlob } from "@/lib/blob-store";
import { DEMO_TRIP_ID, buildDemoTrip } from "@/lib/demo";
import { createServerSupabase, createServiceSupabase } from "@/lib/supabase";
import type { Trip } from "@/lib/types";

/**
 * Trips live in Supabase when it is configured, or on Vercel Blob when a Blob
 * store is attached (the Deploy button creates one). Every write also goes to a
 * two-tier local cache, which is all a deployment with neither has.
 *
 * The map hangs off `globalThis` because route handlers and server components
 * are separate module graphs — a plain module-level map is written by
 * `POST /api/trips` and then read as empty by the trip page. The temp-directory
 * mirror covers the rest: dev server recompiles, process restarts, and reads
 * served by a different serverless instance than the one that built the trip.
 */
const MEMORY_LIMIT = 50;

const globalStore = globalThis as typeof globalThis & {
  __tidefitTrips?: Map<string, Trip>;
};
const memory = (globalStore.__tidefitTrips ??= new Map<string, Trip>());

/** Only /tmp is writable on serverless hosts, which is what tmpdir() resolves to. */
const diskDir = path.join(os.tmpdir(), "tidefit-trips");

function diskPathFor(id: string): string {
  // Ids are generated by randomUUID, but this is a filesystem path either way.
  return path.join(diskDir, `${id.replace(/[^a-zA-Z0-9-]/g, "")}.json`);
}

async function writeToDisk(trip: Trip): Promise<void> {
  try {
    await mkdir(diskDir, { recursive: true });
    await writeFile(diskPathFor(trip.id), JSON.stringify(trip), "utf8");
  } catch (error) {
    console.warn(
      "[tidefit] could not cache trip on disk:",
      error instanceof Error ? error.message : error,
    );
  }
}

async function readFromDisk(id: string): Promise<Trip | null> {
  try {
    return JSON.parse(await readFile(diskPathFor(id), "utf8")) as Trip;
  } catch {
    return null;
  }
}

function rememberInMemory(trip: Trip): void {
  if (memory.size >= MEMORY_LIMIT) {
    const oldest = memory.keys().next().value;
    if (oldest) memory.delete(oldest);
  }
  memory.set(trip.id, trip);
}

/**
 * The client used for `trips` rows. Prefers the service role so RLS can stay
 * owner-only (see supabase/002_tighten_rls.sql); falls back to the cookie-bound
 * anon client, which is what the pre-002 schema needs.
 *
 * Because the service role bypasses RLS, every caller below must scope its own
 * query — there is no policy left to catch a missing filter.
 */
async function tripsClient() {
  return createServiceSupabase() ?? (await createServerSupabase());
}

/** Identity always comes from the user's session, never the service client. */
async function currentUserId(): Promise<string | null> {
  const supabase = await createServerSupabase();
  if (!supabase) return null;
  const { data } = await supabase.auth.getUser();
  return data.user?.id ?? null;
}

export async function saveTrip(trip: Trip): Promise<Trip> {
  rememberInMemory(trip);
  await writeToDisk(trip);

  const supabase = await tripsClient();
  if (!supabase) {
    // Without a durable store a shared link only works on the instance that
    // built the trip, so persist to Blob whenever one is attached.
    if (blobAvailable()) await saveTripBlob(trip);
    return trip;
  }

  const userId = await currentUserId();
  // `trip.id` is a server-minted randomUUID (planner.ts) and is never taken
  // from the request body, so this upsert cannot be aimed at another row.
  const { error } = await supabase.from("trips").upsert({
    id: trip.id,
    user_id: userId,
    destination: trip.input.destination,
    start_date: trip.input.startDate,
    days: trip.input.days,
    sports: trip.input.sports,
    payload: trip,
  });

  if (error) {
    console.warn("[tidefit] could not persist trip to Supabase:", error.message);
  }
  return trip;
}

export async function getTrip(id: string): Promise<Trip | null> {
  if (id === DEMO_TRIP_ID) return buildDemoTrip();

  const cached = memory.get(id);
  if (cached) return cached;

  const onDisk = await readFromDisk(id);
  if (onDisk) {
    rememberInMemory(onDisk);
    return onDisk;
  }

  // A trip id is an unguessable capability: holding the link is what grants
  // access, which is the shared-itinerary behaviour the product intends.
  const supabase = await tripsClient();
  if (!supabase) {
    if (!blobAvailable()) return null;
    const fromBlob = await loadTripBlob(id);
    if (fromBlob) rememberInMemory(fromBlob);
    return fromBlob;
  }

  const { data, error } = await supabase.from("trips").select("payload").eq("id", id).maybeSingle();
  if (error) {
    console.warn("[tidefit] could not load trip from Supabase:", error.message);
    return null;
  }
  if (!data?.payload) return null;

  const trip = data.payload as Trip;
  rememberInMemory(trip);
  return trip;
}

export interface TripSummary {
  id: string;
  destination: string;
  startDate: string;
  days: number;
  sports: string[];
  createdAt: string;
}

export async function listTripsForCurrentUser(): Promise<TripSummary[]> {
  const userId = await currentUserId();
  if (!userId) return [];

  const supabase = await tripsClient();
  if (!supabase) return [];

  const { data, error } = await supabase
    .from("trips")
    .select("id, destination, start_date, days, sports, created_at")
    // Load-bearing: the service client bypasses RLS, so this filter is the
    // only thing keeping one user's list out of another's.
    .eq("user_id", userId)
    .order("created_at", { ascending: false })
    .limit(20);

  if (error || !data) return [];

  return data.map((row) => ({
    id: row.id as string,
    destination: row.destination as string,
    startDate: row.start_date as string,
    days: row.days as number,
    sports: (row.sports as string[]) ?? [],
    createdAt: row.created_at as string,
  }));
}
